export const ActionTypes = {
  SHOW_DATA: "SHOW_DATA",
  SLIDER_DATA: "SLIDER_DATA",
  SET_PRODUCTS: "SET_PRODUCTS",
  GET_INDIVIDUAL_PRODUCTS: "GET_INDIVIDUAL_PRODUCTS",
  ADD_PRODUCTS_TO_THE_CART: "ADD_PRODUCTS_TO_THE_CART",
  GET_PRODUCTS_FROM_THE_CART: "GET_PRODUCTS_FROM_THE_CART",
  CART_COUNT: "CART_COUNT",
  DELETE_SINGLE_ITEM_FROM_CART: "DELETE_SINGLE_ITEM_FROM_CART",
  DELETE_ALL_PRODUCTS: "DELETE_ALL_PRODUCTS",
};
